### PR TITLE
Bump React to 15.0.0

### PR DESCRIPTION
**Pull request by damassi**
This bumps React to the latest.

### CODE REVIEW

**Comment by ngokevin** [comment]
Wonder if I should just remove peerDeps.

**Comment by ngokevin** [comment]
nvm, forgot it's pretty needed

**Comment by damassi** [comment]
thanks so much -- can you release to NPM? (Trying to fix peer dep issue)

**Comment by ngokevin** [comment]
Done thanks

**Comment by damassi** [comment]
👍

**Pull request merged**
